// SPDX-License-Identifier: MIT
pragma solidity 0.8.31;

import {Test, console2} from "forge-std/Test.sol";

import {BlieverMarket}  from "../../src/BlieverMarket.sol";
import {BlieverMarketBase} from "./BlieverMarketBase.t.sol";

/// @title  BlieverMarket — Gas Profiling Tests
/// @notice Logs gas consumption for the critical hot paths: buy, sell, resolve, claim.
///
///         Purpose
///         ───────
///         • Provides concrete per-function gas figures for Base L2 deployment planning.
///         • Feeds `forge snapshot` — Foundry records every test's gas automatically.
///         • Aids CI regression detection via `forge snapshot --check`.
///
///         There are NO gas-cap assertions in this file.
///         Hard numeric caps belong in the gas snapshot (`.gas-snapshot`) generated by
///         `forge snapshot`, which tracks the gas of every test across the full suite
///         and fails CI if any function's cost increases between commits.
///         Keeping the caps out of test code avoids brittle EVM-version-specific failures
///         while still providing complete regression coverage through the snapshot mechanism.
///
///         How to use
///         ──────────
///         Generate a snapshot:   forge snapshot --evm-version cancun
///         Detect regressions:    forge snapshot --check --evm-version cancun
///         View diff:             forge snapshot --diff .gas-snapshot --evm-version cancun
///
/// @dev    Run: forge test --match-contract BlieverMarket_GasTest --evm-version cancun -vvv --gas-report
contract BlieverMarket_GasTest is BlieverMarketBase {

    /*//////////////////////////////////////////////////////////////
                      GAS — BUY (HOT PATH)
    //////////////////////////////////////////////////////////////*/

    /// @dev Warm buy: second call in the same transaction (warm storage slots).
    function test_gas_buy_2outcomes_1share() public {
        _setupTrader(alice, TRADER_USDC);

        // Warm up storage — first call touches all slots cold
        vm.prank(alice);
        market2.buy(0, SHARE_1, MAX_COST, 0, 0, bytes32(0), bytes32(0));
        usdc.mint(alice, TRADER_USDC); // top up

        // Measure warm call
        uint256 gasBefore = gasleft();
        vm.prank(alice);
        market2.buy(0, SHARE_1, MAX_COST, 0, 0, bytes32(0), bytes32(0));
        uint256 gasUsed = gasBefore - gasleft();

        console2.log("buy() 2-outcome warm gas:", gasUsed);
    }

    /// @dev Cold buy: first call on a fresh market (all slots cold).
    function test_gas_buy_2outcomes_cold() public {
        _setupTrader(alice, TRADER_USDC * 10);

        uint256 gasBefore = gasleft();
        vm.prank(alice);
        market2.buy(0, SHARE_1, MAX_COST, 0, 0, bytes32(0), bytes32(0));
        uint256 gasUsed = gasBefore - gasleft();

        console2.log("buy() 2-outcome cold gas:", gasUsed);
    }

    /// @dev Buy on 7-outcome market (n=7 array passes).
    function test_gas_buy_7outcomes_1share() public {
        _setupTrader(alice, TRADER_USDC);

        // Warm up
        vm.prank(alice);
        market7.buy(0, SHARE_1, MAX_COST, 0, 0, bytes32(0), bytes32(0));
        usdc.mint(alice, TRADER_USDC);

        uint256 gasBefore = gasleft();
        vm.prank(alice);
        market7.buy(0, SHARE_1, MAX_COST, 0, 0, bytes32(0), bytes32(0));
        uint256 gasUsed = gasBefore - gasleft();

        console2.log("buy() 7-outcome warm gas:", gasUsed);
    }

    /*//////////////////////////////////////////////////////////////
                      GAS — SELL (HOT PATH)
    //////////////////////////////////////////////////////////////*/

    /// @dev Standard sell (refund path, no CSS): warm gas measurement.
    function test_gas_sell_standard_2outcomes() public {
        _buy(market2, alice, 0, 3 * SHARE_1);
        usdc.mint(alice, MAX_COST); // top up for any CSS edge case

        // Warm up by selling once
        vm.prank(alice);
        market2.sell(0, SHARE_1, 0, MAX_COST, 0, 0, bytes32(0), bytes32(0));

        uint256 gasBefore = gasleft();
        vm.prank(alice);
        market2.sell(0, SHARE_1, 0, MAX_COST, 0, 0, bytes32(0), bytes32(0));
        uint256 gasUsed = gasBefore - gasleft();

        console2.log("sell() standard warm gas:", gasUsed);
    }

    /// @dev CSS sell on 7-outcome market (most expensive sell path — touches all n outcome slots).
    function test_gas_sell_css_7outcomes() public {
        // Warm up all state: buy into outcome 0 first
        _buy(market7, alice, 0, SHARE_1);
        _setupTrader(alice, TRADER_USDC);

        // Warm up CSS sell
        vm.prank(alice);
        market7.sell(0, 3 * SHARE_1, 0, MAX_COST, 0, 0, bytes32(0), bytes32(0));

        // Buy again to have shares for second measurement
        usdc.mint(alice, TRADER_USDC);
        vm.prank(alice);
        market7.buy(0, SHARE_1, MAX_COST, 0, 0, bytes32(0), bytes32(0));

        uint256 gasBefore = gasleft();
        vm.prank(alice);
        market7.sell(0, 3 * SHARE_1, 0, MAX_COST, 0, 0, bytes32(0), bytes32(0));
        uint256 gasUsed = gasBefore - gasleft();

        console2.log("sell() CSS 7-outcome warm gas:", gasUsed);
    }

    /*//////////////////////////////////////////////////////////////
                    GAS — RESOLVE / CLAIM (SETTLEMENT)
    //////////////////////////////////////////////////////////////*/

    /// @dev resolve() gas (no prior trades, zero payout path).
    function test_gas_resolve_noTrades() public {
        uint256 gasBefore = gasleft();
        vm.prank(resolver);
        market2.resolve(0);
        uint256 gasUsed = gasBefore - gasleft();

        console2.log("resolve() no-trades gas:", gasUsed);
    }

    /// @dev resolve() gas with one prior trade.
    function test_gas_resolve_withTrade() public {
        _buy(market2, alice, 0, SHARE_1);

        uint256 gasBefore = gasleft();
        vm.prank(resolver);
        market2.resolve(0);
        uint256 gasUsed = gasBefore - gasleft();

        console2.log("resolve() with-trade gas:", gasUsed);
    }

    /// @dev claim() gas for a winning trader.
    function test_gas_claim_winner() public {
        _buy(market2, alice, 0, SHARE_1);
        _resolve(market2, 0);

        uint256 gasBefore = gasleft();
        vm.prank(alice);
        market2.claim();
        uint256 gasUsed = gasBefore - gasleft();

        console2.log("claim() winner gas:", gasUsed);
    }

    /*//////////////////////////////////////////////////////////////
                    GAS — VIEWS (READ-ONLY CALLS)
    //////////////////////////////////////////////////////////////*/

    /// @dev getPrice() view gas.
    function test_gas_getPrice() public {
        uint256 gasBefore = gasleft();
        market2.getPrice(0);
        uint256 gasUsed = gasBefore - gasleft();
        console2.log("getPrice() gas:", gasUsed);
    }

    /// @dev getAllPrices() view gas for 7-outcome market.
    function test_gas_getAllPrices_7outcomes() public {
        uint256 gasBefore = gasleft();
        market7.getAllPrices();
        uint256 gasUsed = gasBefore - gasleft();
        console2.log("getAllPrices() 7-outcome gas:", gasUsed);
    }

    /// @dev getBuyCost() view gas.
    function test_gas_getBuyCost() public {
        uint256 gasBefore = gasleft();
        market2.getBuyCost(0, SHARE_1);
        uint256 gasUsed = gasBefore - gasleft();
        console2.log("getBuyCost() gas:", gasUsed);
    }

    /// @dev getMarketStatus() view gas.
    function test_gas_getMarketStatus() public {
        uint256 gasBefore = gasleft();
        market2.getMarketStatus();
        uint256 gasUsed = gasBefore - gasleft();
        console2.log("getMarketStatus() gas:", gasUsed);
    }
}
