"use client";

/**
 * lib/crypto/nsec-storage.ts
 *
 * CLIENT-ONLY MODULE — requires IndexedDB, Web Crypto, and WebAuthn (PRF strategy).
 * The "use client" directive above prevents Next.js from bundling this on the server.
 *
 * Encrypted persistence of the Nostr secret key (nsec) in IndexedDB.
 *
 * ─── Storage Strategies ───────────────────────────────────────────────────────
 *
 *   "prf" (preferred) — WebAuthn PRF Extension
 *   ───────────────────────────────────────────
 *   The browser's authenticator (Touch ID / Face ID / Windows Hello / FIDO2
 *   security key) evaluates a fixed PRF input and returns 32 bytes of
 *   deterministic key material that is unique per credential + origin.
 *
 *   What is stored in IndexedDB:
 *     • ciphertext  (AES-256-GCM encrypted nsec)
 *     • iv          (random 12-byte nonce, safe to store)
 *     • credentialId (base64url — identifies the passkey, not the key)
 *
 *   What is NOT stored anywhere:
 *     • The AES key bytes — the authenticator re-derives them on each unlock.
 *     • The nsec plaintext.
 *
 *   Security property: decryption requires both the IndexedDB ciphertext AND
 *   the authenticator. If the IndexedDB profile is exfiltrated without the
 *   device authenticator, decryption is not possible.
 *
 *   "webcrypto" (fallback) — Random AES-256-GCM Key
 *   ─────────────────────────────────────────────────
 *   A random AES-256-GCM CryptoKey is generated by Web Crypto. IndexedDB
 *   can store CryptoKey objects natively (structured clone). The key is
 *   `extractable: false`, preventing its raw bytes from being read by JS.
 *
 *   What is stored in IndexedDB:
 *     • ciphertext  (AES-256-GCM encrypted nsec)
 *     • iv          (random 12-byte nonce)
 *     • cryptoKey   (non-extractable CryptoKey, stored as a structured clone)
 *
 *   Security property: the raw key never appears as JS bytes. However, the
 *   key is stored in the same IDB profile as the ciphertext, so an attacker
 *   who dumps the IDB profile may be able to reconstruct the key via the
 *   browser's internal key storage. This is significantly weaker than PRF.
 *   Use only when PRF is unavailable (e.g., Firefox as of 2024).
 *
 * ─── IndexedDB Schema ────────────────────────────────────────────────────────
 *   Database:   "bliever"       (IDB_DB_NAME)
 *   Version:    1               (IDB_DB_VERSION)
 *   Object store: "keys"        (IDB_STORE_NAME)
 *   Record key: "nsec_bundle"   (NSEC_RECORD_KEY)
 *   Record value: NsecIdbRecord (see below)
 */

import {
  toBase64,
  fromBase64,
  toBase64Url,
  fromBase64Url,
} from "../nostr/nip01-basic/keys";
import type { NsecStorageHandle, NsecStorageStrategy } from "../binding/schema";

// ─── Constants ────────────────────────────────────────────────────────────────

const IDB_DB_NAME = "bliever";
const IDB_DB_VERSION = 1;
const IDB_STORE_NAME = "keys";
const NSEC_RECORD_KEY = "nsec_bundle";

/**
 * Deterministic PRF input label.
 * The same bytes are used on every credential creation and assertion for the
 * same origin, producing the same PRF output (and therefore the same AES key).
 * Changing this value invalidates all existing PRF-encrypted bundles.
 */
const PRF_SALT: ArrayBuffer = new TextEncoder()
  .encode("bliever-v1:nsec-encryption-key-v1")
  .buffer as ArrayBuffer;

// ─── Internal record shape ────────────────────────────────────────────────────

/** The exact value persisted in IndexedDB under NSEC_RECORD_KEY. */
interface NsecIdbRecord {
  strategy: NsecStorageStrategy;
  /** AES-256-GCM ciphertext of the raw nsec bytes, base64-encoded. */
  ciphertext: string;
  /** Random 12-byte AES-GCM IV, base64-encoded. */
  iv: string;
  /** PRF strategy: base64url-encoded WebAuthn rawId. */
  credentialId?: string;
  /** WebCrypto strategy: non-extractable CryptoKey stored via structured clone. */
  cryptoKey?: CryptoKey;
}

// ─── IndexedDB helpers ────────────────────────────────────────────────────────

function openDb(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(IDB_DB_NAME, IDB_DB_VERSION);
    req.onupgradeneeded = (e) => {
      const db = (e.target as IDBOpenDBRequest).result;
      if (!db.objectStoreNames.contains(IDB_STORE_NAME)) {
        db.createObjectStore(IDB_STORE_NAME);
      }
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error ?? new Error("IDB open failed"));
  });
}

function idbGet<T>(db: IDBDatabase, key: IDBValidKey): Promise<T | undefined> {
  return new Promise((resolve, reject) => {
    const req = db
      .transaction(IDB_STORE_NAME, "readonly")
      .objectStore(IDB_STORE_NAME)
      .get(key);
    req.onsuccess = () => resolve(req.result as T | undefined);
    req.onerror = () => reject(req.error);
  });
}

function idbPut<T>(
  db: IDBDatabase,
  key: IDBValidKey,
  value: T,
): Promise<void> {
  return new Promise((resolve, reject) => {
    const req = db
      .transaction(IDB_STORE_NAME, "readwrite")
      .objectStore(IDB_STORE_NAME)
      .put(value, key);
    req.onsuccess = () => resolve();
    req.onerror = () => reject(req.error);
  });
}

function idbDelete(db: IDBDatabase, key: IDBValidKey): Promise<void> {
  return new Promise((resolve, reject) => {
    const req = db
      .transaction(IDB_STORE_NAME, "readwrite")
      .objectStore(IDB_STORE_NAME)
      .delete(key);
    req.onsuccess = () => resolve();
    req.onerror = () => reject(req.error);
  });
}

// ─── AES-GCM primitives ───────────────────────────────────────────────────────

async function aesgcmEncrypt(
  key: CryptoKey,
  plaintext: Uint8Array,
): Promise<{ ciphertext: string; iv: string }> {
  const iv = crypto.getRandomValues(new Uint8Array(12)); // 96-bit GCM nonce
  // Cast to ArrayBuffer: SubtleCrypto's BufferSource parameter requires ArrayBuffer
  // in strict TypeScript; Uint8Array.buffer returns ArrayBufferLike which is too broad.
  const buf = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv: iv.buffer as ArrayBuffer },
    key,
    plaintext.buffer as ArrayBuffer,
  );
  return { ciphertext: toBase64(new Uint8Array(buf)), iv: toBase64(iv) };
}

async function aesgcmDecrypt(
  key: CryptoKey,
  ciphertext: string,
  iv: string,
): Promise<Uint8Array> {
  const ivBytes = fromBase64(iv);
  const ctBytes = fromBase64(ciphertext);
  // Cast to ArrayBuffer: SubtleCrypto requires ArrayBuffer, not ArrayBufferLike.
  const buf = await crypto.subtle.decrypt(
    { name: "AES-GCM", iv: ivBytes.buffer as ArrayBuffer },
    key,
    ctBytes.buffer as ArrayBuffer,
  );
  return new Uint8Array(buf);
}

// ─── PRF strategy ─────────────────────────────────────────────────────────────

/**
 * Creates a new WebAuthn credential with the PRF extension, derives an AES key
 * from the PRF output, encrypts the nsec, and returns the credential ID + record.
 *
 * Triggers a biometric / PIN prompt on the device.
 */
async function prfCreateAndEncrypt(
  nsec: Uint8Array,
  rpId: string,
  userId: Uint8Array,
): Promise<{ record: NsecIdbRecord; handle: NsecStorageHandle }> {
  const credential = (await navigator.credentials.create({
    publicKey: {
      challenge: crypto.getRandomValues(new Uint8Array(32)),
      rp: { id: rpId, name: "Bliever" },
      user: {
        id: userId,
        name: "bliever-user",
        displayName: "Bliever User",
      },
      pubKeyCredParams: [
        { alg: -7,   type: "public-key" }, // ES256
        { alg: -257, type: "public-key" }, // RS256
      ],
      authenticatorSelection: {
        residentKey: "preferred",
        userVerification: "preferred",
      },
      extensions: {
        // PRF extension: ask authenticator to evaluate PRF_SALT and return
        // 32 bytes of key material bound to this credential + origin.
        prf: { eval: { first: PRF_SALT } },
      },
    },
  })) as PublicKeyCredential | null;

  if (!credential) {
    throw new Error("WebAuthn credential creation was cancelled by the user.");
  }

  // Extract PRF output from extension results.
  const prfOutput = (
    credential.getClientExtensionResults() as {
      prf?: { results?: { first?: ArrayBuffer } };
    }
  ).prf?.results?.first;

  if (!prfOutput) {
    throw new Error(
      "The authenticator does not support the PRF extension. " +
      "Call persistNsec with strategy='webcrypto' as a fallback.",
    );
  }

  // Import the 32-byte PRF output as a non-extractable AES-256-GCM key.
  // The key bytes exist only in this call frame; they are never stored.
  const aesKey = await crypto.subtle.importKey(
    "raw",
    prfOutput,
    { name: "AES-GCM" },
    false, // non-extractable: cannot be exported from SubtleCrypto
    ["encrypt", "decrypt"],
  );

  const { ciphertext, iv } = await aesgcmEncrypt(aesKey, nsec);
  const credentialId = toBase64Url(new Uint8Array(credential.rawId));

  const record: NsecIdbRecord = { strategy: "prf", ciphertext, iv, credentialId };
  const handle: NsecStorageHandle = { strategy: "prf", credentialId };
  return { record, handle };
}

/**
 * Asserts an existing WebAuthn credential to re-derive the PRF-based AES key
 * and decrypt the stored nsec.
 *
 * Triggers a biometric / PIN prompt on the device.
 */
async function prfAssertAndDecrypt(
  record: NsecIdbRecord,
  rpId: string,
): Promise<Uint8Array> {
  if (!record.credentialId) {
    throw new Error("PRF nsec record is missing credentialId.");
  }

  const rawId = fromBase64Url(record.credentialId);

  const assertion = (await navigator.credentials.get({
    publicKey: {
      challenge: crypto.getRandomValues(new Uint8Array(32)),
      rpId,
      allowCredentials: [{ type: "public-key", id: rawId }],
      userVerification: "preferred",
      extensions: {
        prf: { eval: { first: PRF_SALT } },
      },
    },
  })) as PublicKeyCredential | null;

  if (!assertion) {
    throw new Error("WebAuthn assertion was cancelled by the user.");
  }

  const prfOutput = (
    assertion.getClientExtensionResults() as {
      prf?: { results?: { first?: ArrayBuffer } };
    }
  ).prf?.results?.first;

  if (!prfOutput) {
    throw new Error(
      "PRF extension did not return output during assertion. " +
      "The authenticator may not support PRF.",
    );
  }

  const aesKey = await crypto.subtle.importKey(
    "raw",
    prfOutput,
    { name: "AES-GCM" },
    false,
    ["encrypt", "decrypt"],
  );

  return aesgcmDecrypt(aesKey, record.ciphertext, record.iv);
}

// ─── WebCrypto fallback strategy ──────────────────────────────────────────────

async function webCryptoCreateAndEncrypt(
  nsec: Uint8Array,
): Promise<{ record: NsecIdbRecord; handle: NsecStorageHandle }> {
  // Generate a random 256-bit AES-GCM key.
  // extractable: false — raw bytes cannot be exported from SubtleCrypto via JS.
  // IDB stores CryptoKey objects via the structured clone algorithm, so the key
  // persists without ever existing as an ArrayBuffer in application code.
  const aesKey = await crypto.subtle.generateKey(
    { name: "AES-GCM", length: 256 },
    false, // non-extractable
    ["encrypt", "decrypt"],
  );

  const { ciphertext, iv } = await aesgcmEncrypt(aesKey, nsec);

  const record: NsecIdbRecord = {
    strategy: "webcrypto",
    ciphertext,
    iv,
    cryptoKey: aesKey, // stored as structured clone; never leaves as raw bytes
  };
  const handle: NsecStorageHandle = { strategy: "webcrypto" };
  return { record, handle };
}

async function webCryptoDecrypt(record: NsecIdbRecord): Promise<Uint8Array> {
  if (!record.cryptoKey) {
    throw new Error(
      "WebCrypto nsec record is missing the CryptoKey. " +
      "The IndexedDB record may be corrupt.",
    );
  }
  return aesgcmDecrypt(record.cryptoKey, record.ciphertext, record.iv);
}

// ─── Public API ───────────────────────────────────────────────────────────────

export interface PersistNsecOptions {
  /**
   * Encryption strategy.
   * Prefer "prf"; fall back to "webcrypto" if the authenticator does not
   * support the PRF extension (catch the error from "prf" and retry).
   */
  strategy: NsecStorageStrategy;
  /**
   * PRF strategy only: WebAuthn relying-party ID.
   * Must be the hostname of the page origin (e.g. "app.bliever.io").
   * Defaults to `window.location.hostname`.
   */
  rpId?: string;
  /**
   * PRF strategy only: user handle passed to the authenticator.
   * Should be unique per user (e.g. first 16 bytes of SHA-256(npub)).
   * A random value is generated if omitted.
   */
  prfUserId?: Uint8Array;
}

/**
 * Encrypts the nsec with the chosen strategy and persists the bundle to IDB.
 *
 * PRF strategy triggers a biometric / PIN prompt.
 * WebCrypto strategy is silent.
 *
 * @param nsec    Raw 32-byte Nostr secret key. Zero-fill your copy after calling.
 * @param options Persistence configuration.
 * @returns       `NsecStorageHandle` — store this; pass to `recoverNsec` later.
 */
export async function persistNsec(
  nsec: Uint8Array,
  options: PersistNsecOptions,
): Promise<NsecStorageHandle> {
  const {
    strategy,
    rpId = window.location.hostname,
    prfUserId = crypto.getRandomValues(new Uint8Array(16)),
  } = options;

  const { record, handle } =
    strategy === "prf"
      ? await prfCreateAndEncrypt(nsec, rpId, prfUserId)
      : await webCryptoCreateAndEncrypt(nsec);

  const db = await openDb();
  try {
    await idbPut<NsecIdbRecord>(db, NSEC_RECORD_KEY, record);
  } finally {
    db.close();
  }

  return handle;
}

export interface RecoverNsecOptions {
  /**
   * PRF strategy only: WebAuthn relying-party ID used during credential creation.
   * Must match exactly. Defaults to `window.location.hostname`.
   */
  rpId?: string;
}

/**
 * Loads the encrypted nsec bundle from IDB and decrypts it.
 *
 * PRF strategy triggers a biometric / PIN prompt (re-derives the AES key).
 * WebCrypto strategy reads the CryptoKey from IDB and decrypts silently.
 *
 * @param _handle  Handle returned by `persistNsec` (currently advisory;
 *                  strategy is read from the stored record directly).
 * @param options  Recovery options.
 * @returns        Raw 32-byte nsec. Zeroize or discard after use.
 * @throws         If no bundle is stored, or decryption fails.
 */
export async function recoverNsec(
  _handle: NsecStorageHandle,
  options: RecoverNsecOptions = {},
): Promise<Uint8Array> {
  const { rpId = window.location.hostname } = options;

  const db = await openDb();
  let record: NsecIdbRecord | undefined;
  try {
    record = await idbGet<NsecIdbRecord>(db, NSEC_RECORD_KEY);
  } finally {
    db.close();
  }

  if (!record) {
    throw new Error(
      "No nsec bundle found in IndexedDB. The user has not completed onboarding " +
      "on this device, or the IDB record was cleared.",
    );
  }

  return record.strategy === "prf"
    ? prfAssertAndDecrypt(record, rpId)
    : webCryptoDecrypt(record);
}

/**
 * Returns `true` if an encrypted nsec bundle exists in IDB for this origin.
 * Does NOT decrypt — safe to call without triggering a biometric prompt.
 * Use to gate "onboarding required" vs "recover session" UI logic.
 */
export async function hasStoredNsec(): Promise<boolean> {
  try {
    const db = await openDb();
    let record: unknown;
    try {
      record = await idbGet(db, NSEC_RECORD_KEY);
    } finally {
      db.close();
    }
    return record !== undefined;
  } catch {
    return false;
  }
}

/**
 * Permanently removes the encrypted nsec bundle from IDB.
 *
 * ⚠️  IRREVERSIBLE without an external backup mechanism.
 * After calling this, the user's Nostr identity cannot be recovered on this
 * device. Only call during deliberate account deletion or device reset flows.
 */
export async function clearStoredNsec(): Promise<void> {
  const db = await openDb();
  try {
    await idbDelete(db, NSEC_RECORD_KEY);
  } finally {
    db.close();
  }
}